version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/cinema-api-mod
    steps:
      - checkout
      - run:
          name: Test Packages
          command: chmod 744 scripts/test.sh
  
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/cinema-api-mod
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install Docker Client
      #     command: |
      #       set -x
      #       VERSION="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VERSION.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VERSION.tgz
      #       mv /tmp/docker/* /usr/bin
      - run:
          name: Build Images
          command: |
            chmod 744 scripts/build.sh && scripts/build.sh
      - run:
          name: Login to Docker
          command: |
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              sudo docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
            else
              docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
            fi
      - run:
          name: Deploy Images to Docker Hub
          command: chmod 744 scripts/deploy.sh

workflows:
  version: 2
  
  update:
    jobs:
      - test
      - deploy